**To create the Matrix**

In [3]:
import numpy as np

# 1-D array
arr1 = np.array([1,2,3,4,5])
print("1-dim", arr1, sep='\n', end='\n\n')

# 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2-dim", arr2, sep='\n', end='\n\n')

# Multi-D array (3x3)
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Mul-dim", arr3, sep='\n', end='\n\n')


1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

Mul-dim
[[1 2 3]
 [4 5 6]
 [7 8 9]]



👉 np.zeros((2,3)) makes a 2 row × 3 column array filled with 0.0


👉 print will show it

In [ ]:
import numpy as np 


zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


👉 np.ones((2,3)) makes a 2 row × 3 column array filled with 1.0


👉 print will show it

In [ ]:
import numpy as np 

zeros = np.ones((2,3))
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]]


👉 np.identity(6) makes a 6 × 6 square matrix


👉 All diagonal elements = 1.0


👉 All other elements = 0.0

In [9]:
import numpy as np 

zeros = np.identity(6)
print(zeros)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


👉 np.full((5,6), "Booked") makes a 5 row × 6 column array


👉 Every place is filled with the word "Booked"

In [11]:
import numpy as np 

full_array = np.full((5,6),"Booked")

print(full_array)

[['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']]


👉 np.arange(start, stop, step)

start = 10

stop = 100 (not included)

step = 2

👉 So it makes numbers from 10 to 98, jumping by 2.

In [15]:
import numpy as np 

range_arr = np.arange(10,100,2)

print(range_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
