**To create the Matrix**

In [3]:
import numpy as np

# 1-D array
arr1 = np.array([1,2,3,4,5])
print("1-dim", arr1, sep='\n', end='\n\n')

# 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2-dim", arr2, sep='\n', end='\n\n')

# Multi-D array (3x3)
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Mul-dim", arr3, sep='\n', end='\n\n')


1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

Mul-dim
[[1 2 3]
 [4 5 6]
 [7 8 9]]



👉 np.zeros((2,3)) makes a 2 row × 3 column array filled with 0.0


👉 print will show it

In [ ]:
import numpy as np 


zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


👉 np.ones((2,3)) makes a 2 row × 3 column array filled with 1.0


👉 print will show it

In [ ]:
import numpy as np 

zeros = np.ones((2,3))
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]]


👉 np.identity(6) makes a 6 × 6 square matrix


👉 All diagonal elements = 1.0


👉 All other elements = 0.0

In [9]:
import numpy as np 

zeros = np.identity(6)
print(zeros)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


👉 np.full((5,6), "Booked") makes a 5 row × 6 column array


👉 Every place is filled with the word "Booked"

In [11]:
import numpy as np 

full_array = np.full((5,6),"Booked")

print(full_array)

[['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']]


👉 np.arange(start, stop, step)

start = 10

stop = 100 (not included)

step = 2

👉 So it makes numbers from 10 to 98, jumping by 2.

In [15]:
import numpy as np 

range_arr = np.arange(10,100,2)

print(range_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


👉 np.linspace(start, stop, num)

start = 1

stop = 100 (included)

num = 12 → total 12 values

👉 It divides the range 1 to 100 into 12 equal parts.
👉 Values are evenly spaced.

In [20]:
import numpy as np 

lin_space = np.linspace(1,100,12)

print(lin_space)

[  1.  10.  19.  28.  37.  46.  55.  64.  73.  82.  91. 100.]


👉 np.random.randint(low, high, size)

low = 1 → starting number (included)

high = 6 → ending number (not included)

size = (5,5) → shape → 5 rows × 5 columns

👉 So it makes a 5×5 matrix with random integers between 1 and 5.
👉 Each time you run, numbers will change.

In [23]:
import numpy as np 

rand_int = np.random.randint(1, 6, (5,5))

print(rand_int)

[[5 1 3 2 4]
 [4 5 5 5 2]
 [1 4 5 2 5]
 [2 5 3 3 1]
 [4 1 5 3 1]]


👉 np.random.randint(low, high)

low = 1 → starting number (included)

high = 10 → ending number (not included)

👉 It generates a single random integer between 1 and 9.
👉 Each time you run it, the number will change.

In [26]:
import numpy as np 

rand_int = np.random.randint(1,10)

print(rand_int)

5


👉 np.random.rand(d1, d2, ...)

Creates an array of random floats between 0 and 1

Shape = (1,3) → 1 row × 3 columns

In [29]:
import numpy as np 

rand_float = np.random.rand(10,3)

print(rand_float)

[[0.45763305 0.66329656 0.83010555]
 [0.83761492 0.4349278  0.03237251]
 [0.88586862 0.3537047  0.92460732]
 [0.13508021 0.91060541 0.27407683]
 [0.12483283 0.9102353  0.58101076]
 [0.87751523 0.22408146 0.24295267]
 [0.72824209 0.60855454 0.16172392]
 [0.49517236 0.6708484  0.12721126]
 [0.93995995 0.93453929 0.6662584 ]
 [0.43043112 0.56127561 0.24772231]]


👉 np.random.randn(3,3)

Creates a 3×3 array

Numbers are random floats from a normal (Gaussian) distribution

Mean ≈ 0, Standard deviation ≈ 1

In [30]:
import numpy as np 

random_norm = np.random.randn(3, 3)

print(random_norm)

[[ 0.52201155  0.22522393  0.65455982]
 [ 0.67839853 -1.39666462 -0.68539169]
 [ 0.35267696 -0.42953342 -0.22790321]]


👉 np.random.choice(array, size)

Picks random elements from the given array/list

size = 2 → selects 2 random items

In [31]:
import numpy as np

rand_choice = np.random.choice(['kohli','Rajat', 'Jithesh', 'Salt'], 2)

print(rand_choice)

['kohli' 'Jithesh']


👉 np.random.seed(10)

Sets the random number generator to a fixed state

Ensures that the same random numbers are generated every time

👉 np.random.randint(6)

Generates one random integer from 0 to 5 (6 not included)

In [ ]:
import numpy as np 

np.random.seed(10)

rand_arr = np.random.randint(6)

print(rand_arr)

4


👉 arr.shape

Shows the shape of the array → (rows, columns)

In [50]:
import numpy as np 

arr = np.array([[1, 2, 3], [10, 11, 10], [4, 5, 6]])
print(arr.shape)

(3, 3)


👉 arr.reshape(3,3)

Changes the shape of the array to 3 rows × 3 columns

The data remains the same, only the layout changes

In [49]:
reshaped = arr.reshape(3, 3)
print(reshaped)

[[ 1  2  3]
 [10 11 10]
 [ 4  5  6]]


👉 arr.flatten()

Converts a multi-dimensional array into a 1-dimensional array

Keeps all the elements in row-wise order

Original array:

In [52]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])

flattened = arr.flatten()

print(flattened)

[1 2 3 4 5 6]


In [54]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])

trans_arr = arr.T

print(trans_arr)

[[1 4]
 [2 5]
 [3 6]]


In [55]:
import numpy as np 

arr = np.array([10, 20, 50, 60, 45, 78])

print(arr[0])
print(arr[-1])
print(arr[::-1])
print(arr[1:3])
print(arr[4:6])

10
78
[78 45 60 50 20 10]
[20 50]
[45 78]


Explanation:

matrix[1,0]

Row 1 (second row), Column 0 (first column)

Value = 40

matrix[0:2, 1]

Rows 0 and 1 (first two rows), Column 1 (second column)

Values = [20, 50]

matrix[0:2, 1:3]

Rows 0 and 1 (first two rows), Columns 1 and 2 (second and third columns)

Shorter Version

[row, column] → single element

[row_slice, column_index] → subset of a column

[row_slice, column_slice] → subset of rows and columns

In [61]:
import numpy as np 

matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[1,0])

print("\n")
print(matrix[0:2, 1])

print("\n")
print(matrix[0:2, 1:3])


40


[20 50]


[[20 30]
 [50 60]]
