**To create the Matrix**

In [3]:
import numpy as np

# 1-D array
arr1 = np.array([1,2,3,4,5])
print("1-dim", arr1, sep='\n', end='\n\n')

# 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2-dim", arr2, sep='\n', end='\n\n')

# Multi-D array (3x3)
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Mul-dim", arr3, sep='\n', end='\n\n')


1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

Mul-dim
[[1 2 3]
 [4 5 6]
 [7 8 9]]



👉 np.zeros((2,3)) makes a 2 row × 3 column array filled with 0.0


👉 print will show it

In [ ]:
import numpy as np 


zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


👉 np.ones((2,3)) makes a 2 row × 3 column array filled with 1.0


👉 print will show it

In [ ]:
import numpy as np 

zeros = np.ones((2,3))
print(zeros)

[[1. 1. 1.]
 [1. 1. 1.]]


👉 np.identity(6) makes a 6 × 6 square matrix


👉 All diagonal elements = 1.0


👉 All other elements = 0.0

In [9]:
import numpy as np 

zeros = np.identity(6)
print(zeros)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


👉 np.full((5,6), "Booked") makes a 5 row × 6 column array


👉 Every place is filled with the word "Booked"

In [11]:
import numpy as np 

full_array = np.full((5,6),"Booked")

print(full_array)

[['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']
 ['Booked' 'Booked' 'Booked' 'Booked' 'Booked' 'Booked']]


👉 np.arange(start, stop, step)

start = 10

stop = 100 (not included)

step = 2

👉 So it makes numbers from 10 to 98, jumping by 2.

In [15]:
import numpy as np 

range_arr = np.arange(10,100,2)

print(range_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


👉 np.linspace(start, stop, num)

start = 1

stop = 100 (included)

num = 12 → total 12 values

👉 It divides the range 1 to 100 into 12 equal parts.
👉 Values are evenly spaced.

In [20]:
import numpy as np 

lin_space = np.linspace(1,100,12)

print(lin_space)

[  1.  10.  19.  28.  37.  46.  55.  64.  73.  82.  91. 100.]


👉 np.random.randint(low, high, size)

low = 1 → starting number (included)

high = 6 → ending number (not included)

size = (5,5) → shape → 5 rows × 5 columns

👉 So it makes a 5×5 matrix with random integers between 1 and 5.
👉 Each time you run, numbers will change.

In [23]:
import numpy as np 

rand_int = np.random.randint(1, 6, (5,5))

print(rand_int)

[[5 1 3 2 4]
 [4 5 5 5 2]
 [1 4 5 2 5]
 [2 5 3 3 1]
 [4 1 5 3 1]]


👉 np.random.randint(low, high)

low = 1 → starting number (included)

high = 10 → ending number (not included)

👉 It generates a single random integer between 1 and 9.
👉 Each time you run it, the number will change.

In [26]:
import numpy as np 

rand_int = np.random.randint(1,10)

print(rand_int)

5


👉 np.random.rand(d1, d2, ...)

Creates an array of random floats between 0 and 1

Shape = (1,3) → 1 row × 3 columns

In [29]:
import numpy as np 

rand_float = np.random.rand(10,3)

print(rand_float)

[[0.45763305 0.66329656 0.83010555]
 [0.83761492 0.4349278  0.03237251]
 [0.88586862 0.3537047  0.92460732]
 [0.13508021 0.91060541 0.27407683]
 [0.12483283 0.9102353  0.58101076]
 [0.87751523 0.22408146 0.24295267]
 [0.72824209 0.60855454 0.16172392]
 [0.49517236 0.6708484  0.12721126]
 [0.93995995 0.93453929 0.6662584 ]
 [0.43043112 0.56127561 0.24772231]]


👉 np.random.randn(3,3)

Creates a 3×3 array

Numbers are random floats from a normal (Gaussian) distribution

Mean ≈ 0, Standard deviation ≈ 1

In [30]:
import numpy as np 

random_norm = np.random.randn(3, 3)

print(random_norm)

[[ 0.52201155  0.22522393  0.65455982]
 [ 0.67839853 -1.39666462 -0.68539169]
 [ 0.35267696 -0.42953342 -0.22790321]]


👉 np.random.choice(array, size)

Picks random elements from the given array/list

size = 2 → selects 2 random items

In [31]:
import numpy as np

rand_choice = np.random.choice(['kohli','Rajat', 'Jithesh', 'Salt'], 2)

print(rand_choice)

['kohli' 'Jithesh']


👉 np.random.seed(10)

Sets the random number generator to a fixed state

Ensures that the same random numbers are generated every time

👉 np.random.randint(6)

Generates one random integer from 0 to 5 (6 not included)

In [ ]:
import numpy as np 

np.random.seed(10)

rand_arr = np.random.randint(6)

print(rand_arr)

4


👉 arr.shape

Shows the shape of the array → (rows, columns)

In [50]:
import numpy as np 

arr = np.array([[1, 2, 3], [10, 11, 10], [4, 5, 6]])
print(arr.shape)

(3, 3)


👉 arr.reshape(3,3)

Changes the shape of the array to 3 rows × 3 columns

The data remains the same, only the layout changes

In [49]:
reshaped = arr.reshape(3, 3)
print(reshaped)

[[ 1  2  3]
 [10 11 10]
 [ 4  5  6]]


👉 arr.flatten()

Converts a multi-dimensional array into a 1-dimensional array

Keeps all the elements in row-wise order

Original array:

In [52]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])

flattened = arr.flatten()

print(flattened)

[1 2 3 4 5 6]


In [54]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])

trans_arr = arr.T

print(trans_arr)

[[1 4]
 [2 5]
 [3 6]]


In [55]:
import numpy as np 

arr = np.array([10, 20, 50, 60, 45, 78])

print(arr[0])
print(arr[-1])
print(arr[::-1])
print(arr[1:3])
print(arr[4:6])

10
78
[78 45 60 50 20 10]
[20 50]
[45 78]


Explanation:

matrix[1,0]

Row 1 (second row), Column 0 (first column)

Value = 40

matrix[0:2, 1]

Rows 0 and 1 (first two rows), Column 1 (second column)

Values = [20, 50]

matrix[0:2, 1:3]

Rows 0 and 1 (first two rows), Columns 1 and 2 (second and third columns)

Shorter Version

[row, column] → single element

[row_slice, column_index] → subset of a column

[row_slice, column_slice] → subset of rows and columns

In [ ]:
import numpy as np 

matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(matrix[1,0])

print("\n")
print(matrix[0:2, 1])

print("\n")
print(matrix[0:2, 1:3])


40


[20 50]


[[20 30]
 [50 60]]


Explanation:

1D array (arr)

np.sum(arr) → 10+20+50+60+45+78 = 263

np.mean(arr) → 263 ÷ 6 = 43.83

np.median(arr) → middle value after sorting [10, 20, 45, 50, 60, 78] → 47.5

2D array (arr1)

np.sum(arr1) → sum of all numbers = 10+20+30+40+50+60+70+80+90 = 450

np.mean(arr1) → 450 ÷ 9 = 50.0

np.median(arr1) → middle value after sorting [10,20,30,40,50,60,70,80,90] → 50

✅ Notes:

np.sum() → total sum

np.mean() → average

np.median() → middle value

In [4]:
import numpy as np 

arr = np.array([10, 20, 50, 60, 45, 78])
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print("\n")
print(np.sum(arr1))
print(np.mean(arr1))
print(np.median(arr1))


263
43.833333333333336
47.5


450
50.0
50.0


Explanation

Mean → Sum all elements and divide by number of elements
Example: 1 + 2 + 3 + 4 + 5 divided by 5 = 3.0

Variance → Average of squared differences from the mean
Example: (1-3)^2 + (2-3)^2 + (3-3)^2 + (4-3)^2 + (5-3)^2 divided by 5 = 2.0

Standard Deviation → Square root of variance
Example: square root of 2.0 = 1.414

✅ Summary:

Mean → Central value

Variance → Spread of numbers

Standard Deviation → Deviation from mean

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(np.mean(a))
print(np.var(a))
print(np.std(a))

3.0
2.0
1.4142135623730951


np.min(arr) → Finds the smallest value in the array → 10

np.max(arr) → Finds the largest value in the array → 78

summary:

Minimum → smallest number

Maximum → largest number

In [ ]:
import numpy as np

arr = np.array([10, 20, 50, 60, 45, 78])


print(np.min(arr))
print(np.max(arr))

10
78


np.cumsum(arr) → Calculates the running sum of elements
Example: [4, 4+9=13, 13+16=29, 29+25=54, 54+36=90]

np.cumprod(arr) → Calculates the running product of elements
Example: [4, 4×9=36, 36×16=576, 576×25=14400, 14400×36=518400]

✅ Summary:

Cumulative sum → running total

Cumulative product → running multiplication

In [8]:
import numpy as np 

arr = np.array([4, 9, 16, 25, 36])

print(np.cumsum(arr))
print("\n")
print(np.cumprod(arr))

[ 4 13 29 54 90]


[     4     36    576  14400 518400]


arr <= 30 → Checks each element, returns True if condition is met, otherwise False

arr[arr <= 30] → Uses the boolean array to select only elements ≤ 30

✅ Summary:

Boolean indexing → filter elements based on condition

Useful for selecting data from arrays quickly

In [9]:
import numpy as np 

arr = np.array([10, 20, 30, 40, 50])

print(arr <=30)
print("\n")
print(arr[arr <=30])

[ True  True  True False False]


[10 20 30]


np.sort(arr) → Returns a sorted copy of the array in ascending order

Original array remains unchanged

Useful for organizing data or preparing for further analysis

✅ Summary:

Sort → Arrange elements in order (ascending by default)

In [ ]:
import numpy as np 

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
sorted_arr = np.sort(arr)

print(sorted_arr)

[1 1 2 3 4 5 6 9]


np.unique(arr) → Returns all unique elements of the array in sorted order

Removes duplicates automatically

Useful for finding distinct values in data

✅ Summary:

Unique → Distinct elements of an array, sorted by default

In [ ]:
import numpy as np 


arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
unique_vals = np.unique(arr)


print(unique_vals)

[1 2 3 4 5 6 9]


View (arr.view()) → Creates a new array object but shares the same data

Changing view_arr also changes arr

Copy (arr.copy()) → Creates a completely independent array

Changing copy_arr does not affect arr

✅ Summary:

Use view to save memory but linked to original

Use copy when you want independent data

In [17]:
import numpy as np

arr = np.array([10, 20, 30])


view_arr = arr.view()
view_arr[0] = 100
print(arr,view_arr)

print("\n")
copy_arr = arr.copy()
copy_arr[0] = 200
print(arr,copy_arr)

[100  20  30] [100  20  30]


[100  20  30] [200  20  30]


**Matrix Multiplication**

np.dot(A, B) → Performs matrix multiplication

For 2×2 matrices:

Element at (0,0) → 15 + 27 = 19

Element at (0,1) → 16 + 28 = 22

Element at (1,0) → 35 + 47 = 43

Element at (1,1) → 36 + 48 = 50

✅ Summary:

np.dot → Multiply two arrays (vectors or matrices) according to linear algebra rules

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


print(np.dot(A, B))

[[19 22]
 [43 50]]


**Matrix Determinent**

np.linalg.det(arr1) → Computes the determinant of a square matrix

Determinant is a scalar value that can indicate:

If det = 0 → matrix is singular (not invertible)

If det ≠ 0 → matrix is invertible

✅ Summary:

Determinant → Scalar value representing certain properties of the matrix

In [23]:
import numpy as np

arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])


print(np.linalg.det(arr1))

-4.263256414560599e-12


**Matrix Inverse**

np.linalg.det(arr1) → Computes the determinant of a square matrix

Determinant is a scalar value that can indicate:

If det = 0 → matrix is singular (not invertible)

If det ≠ 0 → matrix is invertible

✅ Summary:

Determinant → Scalar value representing certain properties of the matrix

In [22]:
import numpy as np

arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(np.linalg.inv(arr1))

[[ 7.03687442e+13 -1.40737488e+14  7.03687442e+13]
 [-1.40737488e+14  2.81474977e+14 -1.40737488e+14]
 [ 7.03687442e+13 -1.40737488e+14  7.03687442e+13]]


**eigenValues and eigen vectors**

np.linalg.eig(arr1) → Returns eigenvalues and eigenvectors of a square matrix

Eigenvalues → Scalars λ such that A*v = λ*v

Eigenvectors → Vectors v that satisfy the equation above

✅ Summary:

Eigenvalues → Show the “stretching factor” of the matrix

Eigenvectors → Directions in which the matrix acts as a simple scaling

In [41]:
import numpy as np

arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

eigenvalues, eigenvectors = np.linalg.eig(arr1)
print("eigenvalues")
print(eigenvalues)
print("\n")
print(eigenvectors)

eigenvalues
[ 1.61168440e+02 -1.11684397e+01  8.30661129e-16]


[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


np.linalg.eig(arr1) → Returns both eigenvalues and eigenvectors

Using _ ignores eigenvalues, keeping only eigenvectors

Eigenvectors → Directions in which the matrix acts as simple scaling

✅ Summary:

_ → placeholder to ignore unwanted output

Eigenvectors → Show the “direction” of matrix transformation

In [39]:
import numpy as np

arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

_,eigenvectors = np.linalg.eig(arr1)

print(eigenvectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


np.linalg.solve(A, C) → Solves the linear system A * x = C

A → Coefficient matrix

C → Constant terms vector

Returns solution vector x that satisfies the equation

✅ Summary:

Use np.linalg.solve instead of manually calculating inverse

Efficient and accurate for solving linear systems

In [32]:
import numpy as np

A = np.array([[3, 1],
              [1, 4]])

C = np.array([5, 11])

solution = np.linalg.solve(A, C)
print(solution)   


[0.81818182 2.54545455]


np.vstack((A, B)) → Stacks arrays vertically (adds rows)

[[1 2]

 [3 4]

 [5 6]

 [7 8]]


np.hstack((A, B)) → Stacks arrays horizontally (adds columns)

[[1 2 5 6]

 [3 4 7 8]]


✅ Summary:

Vertical stack → rows are combined

Horizontal stack → columns are combined

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print(vertical_stack)
print("\n")
print(horizontal_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


np.split(array, n) → Splits the array into n equal parts

Each part is returned as a separate array

Original array: [1, 2, 3, 4, 5, 6]

Split into 6 parts → Each element becomes its own array

✅ Summary:

Use np.split to divide arrays into multiple sub-arrays

Works for 1D and 2D arrays

In [37]:
split_arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 6)

print(split_arr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
